apiVersion: v1
kind: Service
metadata:
  name: k8s-topo-service
  labels:
    run: k8s-topo-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: k8s-topo

---

apiVersion: v1
kind: Pod
metadata:
  name: k8s-topo
  labels:
    app: k8s-topo
spec:
  terminationGracePeriodSeconds: 0
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/master: "true"
  containers:
  - name: k8s-topo
    image: networkop/k8s-topo
    imagePullPolicy: Always
    ports:
      - containerPort: 80