apiVersion: v1
kind: Service
metadata:
  name: k8s-topo-service
  labels:
    run: k8s-topo-service
spec:
  type: NodePort 
  ports:
  - port: 80
    nodePort: 32080
    protocol: TCP
  selector:
    app: k8s-topo

---

apiVersion: v1
kind: Pod
metadata:
  name: k8s-topo
  labels:
    app: k8s-topo
spec:
  terminationGracePeriodSeconds: 0
  hostNetwork: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  containers:
  - name: k8s-topo
    image: networkop/k8s-topo
    imagePullPolicy: Always
    ports:
      - containerPort: 80
    volumeMounts:
      - name: kube-config
        mountPath: /root/.kube/
  terminationGracePeriodSeconds: 0
  volumes:
    - name: kube-config
      hostPath:
        path: /root/.kube/